apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 1  # Number of instances (pods) to run
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: ganesh2soft/apigateway:latest # Replace with your Docker image name
        imagePullPolicy: IfNotPresent  
        
        ports:
        - containerPort: 9200  # Port that your Spring Boot application listens on inside the container
