apiVersion: v1
kind: Service
metadata:
  name: articlesprbootapp-service
spec:
  selector:
    app: articlesprbootapp  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80  # Service port (port exposed on the Service)
      targetPort: 8084  # Port your application is listening on inside the container
      nodePort: 30020  # NodePort number (replace with your desired port number)
  type: NodePort  # Expose the Service on a NodePort
