apiVersion: apps/v1
kind: Deployment
metadata:
  name: articlesprbootapp-deployment
spec:
  replicas: 1  # Number of instances (pods) to run
  selector:
    matchLabels:
      app: articlesprbootapp
  template:
    metadata:
      labels:
        app: articlesprbootapp
    spec:
      containers:
      - name: articlesprbootapp
        image: ganesh2soft/articlesprbootapp:latest # Replace with your Docker image name
        imagePullPolicy: IfNotPresent  
        
        ports:
        - containerPort: 8084  # Port that your Spring Boot application listens on inside the container
