                        FROM eclipse-temurin:latest
						
						RUN pwd
						
						RUN ls -al
						
						COPY  target/articlesprbootapp-1.0.jar /articlesprbootapp-1.0/articlesprbootapp-1.0.jar
						
						WORKDIR /articlesprbootapp-1.0
						
						RUN pwd
						
						RUN ls -al
                                             
                    				
						
                        CMD ["java", "-jar", "articlesprbootapp-1.0.jar"]
                    