apiVersion: apps/v1
kind: Deployment
metadata:
  name: articlesprbootapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: articlesprbootapp
  template:
    metadata:
      labels:
        app: articlesprbootapp
    spec:
      containers:
      - name: articlesprbootapp
        image: articlesprbootapp:latest
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: articlesprbootapp-service
spec:
  type: NodePort
  selector:
    app: articlesprbootapp
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30008
