apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-service
spec:
  selector:
    app: eurekaserver  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80  # Service port (port exposed on the Service)
      targetPort: 8761  # Port your application is listening on inside the container
      nodePort: 30050  # NodePort number (replace with your desired port number)
  type: NodePort  # Expose the Service on a NodePort
